CREATE TABLE PRODUTOS (
    ID INT IDENTITY(1,1) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(250) NULL,
    DATAVENCIMENTO DATETIME NULL,
    PRECO MONEY NOT NULL,
    UNIDADE VARCHAR(10) NOT NULL,
    QUANTIDADEESTOQUE INT NOT NULL,
    CONSTRAINT PK_Produto PRIMARY KEY (ID)
);